parameters:
  rules:
    '@PSR2': false
    array_indentation: true
    array_syntax:
      syntax: long
    binary_operator_spaces: true
    blank_line_after_opening_tag: true
    blank_line_before_statement:
      statements:
        - case
        - break
        - continue
        - declare
        - return
        - throw
        - try
    braces:
      allow_single_line_closure: true
      position_after_functions_and_oop_constructs: same
    cast_spaces: true
    class_attributes_separation: false
    declare_equal_normalize:
      space: single
    Drupal/blank_line_before_end_of_class: true
    Drupal/control_structure_braces_else: true
    Drupal/inline_comment_spacer: true
    # WIP
    #Drupal/line_length:
    #  line_length: 80
    #  inline_short_lines: false
    #  break_long_lines: true
    Drupal/try_catch_block: true
    Drupal/uppercase_constants: true
    elseif: true
    fully_qualified_strict_types: true
    function_declaration:
      closure_function_spacing: one
    include: true
    # Disable this rules - it conflicts with 'braces'
    # indentation_type: true
    is_null: true
    lowercase_static_reference: true
    method_argument_space: true
    native_function_invocation: false
    no_blank_lines_after_class_opening: false
    no_closing_tag: true
    no_extra_blank_lines:
      tokens:
        - extra
        - parenthesis_brace_block
        - square_brace_block
        - return
        - throw
        - use
        - use_trait
    no_short_echo_tag: true
    no_trailing_whitespace_in_comment: true
    no_unneeded_final_method: true
    no_unused_imports: true
    no_useless_else: true
    ordered_class_elements:
      order:
        - use_trait
        - constant_public
        - constant_protected
        - constant_private
        - property_public
        - property_protected
        - property_private
        - construct
        - destruct
        - magic
        - phpunit
        - method_public
        - method_protected
        - method_private
      sortAlgorithm: alpha
    ordered_imports: ~
    phpdoc_indent: true
    phpdoc_no_empty_return: true
    phpdoc_no_package: true
    phpdoc_no_useless_inheritdoc: true
    phpdoc_order: true
    phpdoc_scalar: true
    phpdoc_separation: true
    phpdoc_single_line_var_spacing: true
    phpdoc_summary: true
    phpdoc_trim: true
    return_type_declaration:
      space_before: none
    single_blank_line_at_eof: true
    single_line_after_imports: true
    switch_case_semicolon_to_colon: true
    switch_case_space: true
    strict_comparison: true
    strict_param: true
    trailing_comma_in_multiline_array: true
    visibility_required: true
    yoda_style:
      equal: false
      identical: false
      less_and_greater: false
      always_move_variable: false
