parameters:
  rules:
    '@PSR2': false
    align_multiline_comment:
      comment_type: all_multiline
    array_indentation: true
    array_syntax:
      syntax: long
    backtick_to_shell_exec: true
    binary_operator_spaces:
      default: single_space
    blank_line_after_opening_tag: true
    blank_line_before_return: false
    blank_line_before_statement:
      statements:
        - break
        - case
        - continue
        - declare
        - default
        - die
        - do
        - exit
        - for
        - foreach
        - goto
        - if
        - include
        - include_once
        - require
        - require_once
        - return
        - switch
        - throw
        - try
        - while
        - yield
    braces:
      allow_single_line_closure: true
      position_after_functions_and_oop_constructs: same
    cast_spaces:
      space: single
    class_attributes_separation: false
    class_definition:
      multi_line_extends_each_single_line: true
    class_keyword_remove: false
    combine_consecutive_issets: true
    combine_consecutive_unsets: true
    combine_nested_dirname: false
    comment_to_phpdoc: true
    compact_nullable_typehint: true
    concat_space:
      spacing: one
    date_time_immutable: true
    declare_equal_normalize:
      space: single
    Drupal/blank_line_before_end_of_class: true
    Drupal/control_structure_braces_else: true
    Drupal/inline_comment_spacer: true
    # WIP
    #Drupal/line_length:
    #  line_length: 80
    #  inline_short_lines: false
    #  break_long_lines: true
    # WIP
    # Drupal/new_line_on_multiline_array: true
    Drupal/try_catch_block: true
    Drupal/uppercase_constants: true
    declare_strict_types: false
    dir_constant: true
    doctrine_annotation_array_assignment:
      operator: ':'
    doctrine_annotation_braces:
      syntax: without_braces
    doctrine_annotation_indentation: true
    doctrine_annotation_spaces:
      after_argument_assignments: false
      after_array_assignments_colon: true
      after_array_assignments_equals: false
      around_parentheses: true
      before_argument_assignments: false
      before_array_assignments_colon: false
      before_array_assignments_equals: false
    elseif: true
    encoding: true
    ereg_to_preg: true
    error_suppression:
      mute_deprecation_error: true
      noise_remaining_usages: true
    escape_implicit_backslashes: true
    explicit_indirect_variable: false
    explicit_string_variable: true
    final_class: false
    final_internal_class: true
    fopen_flag_order: true
    fopen_flags: true
    full_opening_tag: true
    fully_qualified_strict_types: true
    function_declaration:
      closure_function_spacing: one
    function_to_constant: true
    function_typehint_space: true
    general_phpdoc_annotation_remove: false
    hash_to_slash_comment: true
    header_comment: false
    heredoc_indentation: false
    heredoc_to_nowdoc: true
    implode_call: true
    include: true
    # Disable this rules - it conflicts with 'braces'
    # indentation_type: true
    is_null: true
    line_ending: true
    linebreak_after_opening_tag: true
    list_syntax: false
    logical_operators: true
    lowercase_cast: true
    lowercase_keywords: true
    lowercase_static_reference: true
    magic_constant_casing: true
    magic_method_casing: true
    mb_str_functions: true
    method_argument_space:
      ensure_fully_multiline: true
      keep_multiple_spaces_after_comma: false
    method_chaining_indentation: true
    method_separation: false
    modernize_types_casting: true
    multiline_comment_opening_closing: true
    multiline_whitespace_before_semicolons:
      strategy: no_multi_line
    native_constant_invocation: true
    native_function_casing: true
    native_function_invocation:
      include:
        - '@all'
    native_function_type_declaration_casing: true
    new_with_braces: true
    no_alias_functions: true
    no_alternative_syntax: false
    no_binary_string: true
    no_blank_lines_after_class_opening: false
    no_blank_lines_after_phpdoc : false
    no_blank_lines_before_namespace: false
    no_closing_tag: true
    no_empty_comment: true
    no_empty_phpdoc: true
    no_empty_statement: true
    no_extra_blank_lines:
      tokens:
        - break
        - case
        - continue
        - default
        - extra
        - parenthesis_brace_block
        - return
        - square_brace_block
        - switch
        - throw
        - use
        - use_trait
    no_extra_consecutive_blank_lines: false
    no_homoglyph_names: true
    no_leading_import_slash: true
    no_leading_namespace_whitespace: true
    no_mixed_echo_print:
      use: print
    no_multiline_whitespace_around_double_arrow: true
    no_multiline_whitespace_before_semicolons: false
    no_null_property_initialization: true
    no_php4_constructor: false
    no_short_bool_cast: true
    no_short_echo_tag: true
    no_singleline_whitespace_before_semicolons: true
    no_spaces_after_function_name: true
    no_spaces_around_offset: true
    no_spaces_inside_parenthesis: true
    no_superfluous_elseif: true
    no_superfluous_phpdoc_tags: false
    no_trailing_comma_in_list_call: true
    no_trailing_comma_in_singleline_array: true
    no_trailing_whitespace: true
    no_trailing_whitespace_in_comment: true
    no_unneeded_control_parentheses: true
    no_unneeded_curly_braces: true
    no_unneeded_final_method: true
    no_unreachable_default_argument_value: true
    no_unset_cast: true
    no_unset_on_property: true
    no_unused_imports: true
    no_useless_else: true
    no_useless_return: true
    no_whitespace_before_comma_in_array: true
    no_whitespace_in_blank_line: true
    non_printable_character: true
    normalize_index_brace: true
    not_operator_with_space: false
    not_operator_with_successor_space: false
    object_operator_without_whitespace: true
    ordered_class_elements:
      order:
        - use_trait
        - constant_public
        - constant_protected
        - constant_private
        - property_public
        - property_protected
        - property_private
        - construct
        - destruct
        - magic
        - phpunit
        - method_public
        - method_protected
        - method_private
      sortAlgorithm: alpha
    ordered_imports: true
    ordered_interfaces: true
    php_unit_construct: true
    php_unit_dedicate_assert: true
    php_unit_dedicate_assert_internal_type: false
    php_unit_expectation:
      target: newest
    php_unit_fqcn_annotation: true
    php_unit_internal_class:
      types:
        - abstract
        - final
        - normal
    php_unit_method_casing: true
    php_unit_mock: true
    php_unit_mock_short_will_return: true
    php_unit_namespaced:
      target: '5.7'
    php_unit_no_expectation_annotation:
      target: newest
      use_class_const: true
    php_unit_ordered_covers: true
    php_unit_set_up_tear_down_visibility: true
    php_unit_size_class: false
    php_unit_strict: false
    php_unit_test_annotation: true
    php_unit_test_case_static_method_calls:
      call_type: self
    php_unit_test_class_requires_covers: true
    phpdoc_add_missing_param_annotation: false
    phpdoc_align: false
    phpdoc_annotation_without_dot: false
    phpdoc_indent: true
    phpdoc_inline_tag: true
    phpdoc_no_access: true
    phpdoc_no_alias_tag: true
    phpdoc_no_empty_return: true
    phpdoc_no_package: true
    phpdoc_no_useless_inheritdoc: true
    phpdoc_order: true
    phpdoc_return_self_reference: true
    phpdoc_scalar: true
    phpdoc_separation: true
    phpdoc_single_line_var_spacing: true
    phpdoc_summary: true
    phpdoc_to_comment: false
    phpdoc_to_return_type: false
    phpdoc_trim: true
    phpdoc_trim_consecutive_blank_line_separation: true
    phpdoc_types: true
    phpdoc_types_order:
      null_adjustment: always_first
      sort_algorithm: alpha
    phpdoc_var_annotation_correct_order: true
    phpdoc_var_without_name: true
    pow_to_exponentiation: true
    pre_increment: false
    protected_to_private: true
    psr0: false
    psr4: true
    random_api_migration: true
    return_assignment: true
    return_type_declaration:
      space_before: none
    self_accessor: false
    semicolon_after_instruction: true
    set_type_to_cast: true
    short_scalar_cast: true
    silenced_deprecation_error: false
    single_blank_line_at_eof: true
    single_line_after_imports: true
    simple_to_complex_string_variable: true
    simplified_null_return: true
    single_blank_line_before_namespace: true
    single_line_comment_style: true
    single_quote:
      strings_containing_single_quote_chars: false
    single_trait_insert_per_statement: true
    space_after_semicolon: true
    standardize_increment: true
    standardize_not_equals: true
    static_lambda: true
    strict_comparison: true
    strict_param: true
    string_line_ending: true
    switch_case_semicolon_to_colon: true
    switch_case_space: true
    ternary_operator_spaces: true
    ternary_to_null_coalescing: false
    trailing_comma_in_multiline_array: true
    trim_array_spaces: true
    unary_operator_spaces: true
    visibility_required: true
    void_return: false
    whitespace_after_comma_in_array: true
    yoda_style:
      equal: false
      identical: false
      less_and_greater: false
      always_move_variable: false
