imports:
    - { resource: ../../../../drupol/php-conventions/config/php73/grumphp.yml }
    - { resource: tasks.phpcsfixer.config.yml }

parameters:
    # Grumphp license task
    tasks.license.name: LGPL-2.0

    # PHP Code Sniffer parameters.
    tasks.phpcs.exclude: []
    tasks.phpcs.ignore_patterns:
        - vendor/
        - node_modules/
        - tests/fixtures/
        - spec
    tasks.phpcs.triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    tasks.phpcs.whitelist_patterns: []
    tasks.phpcs.standard: ./vendor/drupol/drupal-conventions/config/drupal9/phpcs.xml
    tasks.phpcs.warning_severity: ~

    # PHP CS Fixer parameters
    tasks.phpcsfixer.triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
